#!/bin/bash

if [[ $# -ne 2 ]]
then
	echo 'Ожидалось 2 аргумента имен файлов'
	exit
fi
if [[ -r $1 ]]
then
	if [[ -w $2 ]]
	then
	 echo 'Содержимое файла' $1 'перенаправляется в файл' $2
	 cat $1 >> $2
	else
		if [[ -f $2 ]]
		then
			echo 'Файл' $2 'не доступен для записи'
		else
			echo 'Файл' $2 'не существует'
		fi
	fi
else
	if [[ -f $1 ]]
	then
		echo 'Файл' $1 'не доступен для чтения'
	else
		echo 'Файл' $1 'не существует'
	fi
fi
