#!/bin/bash

trg=7

read -p 'Введите число: ' val

if [[ $val -eq $trg ]]
then 
	echo 'Введенное значение равно допустимому'
elif [[ $val -gt $trg ]]
then 
	echo 'Введенное значение больше допустимого'
else 
	echo 'Введнное значение меньше допустимого'
fi 
